/home/data_shares/ccdd/rt
Traceback (most recent call last):
  File "/home/data_shares/ccdd/revisiting-transfer/src/make_dataframe.py", line 4, in <module>
    from io_fun.data_import import collect_data
  File "/home/data_shares/ccdd/revisiting-transfer/src/io_fun/data_import.py", line 9, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'
Traceback (most recent call last):
  File "/home/data_shares/ccdd/revisiting-transfer/src/make_dataframe.py", line 4, in <module>
    from io_fun.data_import import collect_data
  File "/home/data_shares/ccdd/revisiting-transfer/src/io_fun/data_import.py", line 9, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'
Traceback (most recent call last):
  File "/home/data_shares/ccdd/revisiting-transfer/src/make_dataframe.py", line 4, in <module>
    from io_fun.data_import import collect_data
  File "/home/data_shares/ccdd/revisiting-transfer/src/io_fun/data_import.py", line 9, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'
Traceback (most recent call last):
  File "/home/data_shares/ccdd/revisiting-transfer/src/make_dataframe.py", line 4, in <module>
    from io_fun.data_import import collect_data
  File "/home/data_shares/ccdd/revisiting-transfer/src/io_fun/data_import.py", line 9, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'
Traceback (most recent call last):
  File "/home/data_shares/ccdd/revisiting-transfer/src/make_dataframe.py", line 4, in <module>
    from io_fun.data_import import collect_data
  File "/home/data_shares/ccdd/revisiting-transfer/src/io_fun/data_import.py", line 9, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'
Traceback (most recent call last):
  File "/home/data_shares/ccdd/revisiting-transfer/src/make_dataframe.py", line 4, in <module>
    from io_fun.data_import import collect_data
  File "/home/data_shares/ccdd/revisiting-transfer/src/io_fun/data_import.py", line 9, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'
Traceback (most recent call last):
  File "/home/data_shares/ccdd/revisiting-transfer/src/make_dataframe.py", line 4, in <module>
    from io_fun.data_import import collect_data
  File "/home/data_shares/ccdd/revisiting-transfer/src/io_fun/data_import.py", line 9, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'
Traceback (most recent call last):
  File "/home/data_shares/ccdd/revisiting-transfer/src/make_dataframe.py", line 4, in <module>
    from io_fun.data_import import collect_data
  File "/home/data_shares/ccdd/revisiting-transfer/src/io_fun/data_import.py", line 9, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'
